name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js (14.18.0)
        uses: actions/setup-node@v1
        with:
          node-version: "14.18.0"

      - name: Install Packages
        run: npm ci

      - name: Run Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
